### PR TITLE
Refact 1

### PR DESCRIPTION
**Pull request by trupakufi**

### CODE REVIEW

**Comment by trupakufi** [comment]
Changelog: 

Some Refactor

Change all vars from let to const, cause they does not change anytime.
Create an Object to use on URL builder for transactions and requests.

**Review by smaziano — CHANGES_REQUESTED** [review]
These changes wont scale when version changes. If you're eager to contribute in the project my recommendation would be to think about long term (versions) maintenance.

**Comment by trupakufi** [comment]
How it wont scale ? I will think on it.!

**Comment by smaziano** [comment]
@trupakufi the tests are intended for the version 1 and your pr is focusing defining it "version less".
Other recommendations would be:
1. Elaborate your change log (intents, value and others) so that the maintainer can understand your intent.
2. Make sure your PR's are focused to specific problems.

Following these recommendations will increase the chances for your PR be merged.

**Comment by trupakufi** [comment]
> @trupakufi the tests are intended for the version 1 and your pr is focusing defining it "version less". Other recommendations would be:
> 
> 1. Elaborate your change log (intents, value and others) so that the maintainer can understand your intent.
> 2. Make sure your PR's are focused to specific problems.
> 
> Following these recommendations will increase the chances for your PR be merged.

Allright, i GOT IT, I'll be better at the next time.

**Pull request closed without merging**
